version: '3.8'

services:
  user-db:
    image: postgres:latest
    container_name: devtracker_userdb
    restart: always
    environment:
      POSTGRES_DB: devtracker_userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password12
    ports:
      - "5432:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - devtracker-net

  log-db:
    image: postgres:latest
    container_name: devtracker_logdb
    restart: always
    environment:
      POSTGRES_DB: devtracker_logdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password12
    ports:
      - "5433:5432"
    volumes:
      - log-db-data:/var/lib/postgresql/data
    networks:
      - devtracker-net

  tracking-db:
    image: postgres:latest
    container_name: devtracker_trackingdb
    restart: always
    environment:
      POSTGRES_DB: devtracker_trackingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password12
    ports:
      - "5434:5432"
    volumes:
      - tracking-db-data:/var/lib/postgresql/data
    networks:
      - devtracker-net

  goal-db:
    image: postgres:latest
    container_name: devtracker_goaldb
    restart: always
    environment:
      POSTGRES_DB: devtracker_goaldb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password12
    ports:
      - "5435:5432"
    volumes:
      - goal-db-data:/var/lib/postgresql/data
    networks:
      - devtracker-net

  insight-db:
    image: postgres:latest
    container_name: devtracker_insightdb
    restart: always
    environment:
      POSTGRES_DB: devtracker_insightdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password12
    ports:
      - "5436:5432"
    volumes:
      - insight-db-data:/var/lib/postgresql/data
    networks:
      - devtracker-net

  github-db:
    image: postgres:latest
    container_name: devtracker_githubdb
    restart: always
    environment:
      POSTGRES_DB: devtracker_githubdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password12
    ports:
      - "5437:5432"
    volumes:
      - github-db-data:/var/lib/postgresql/data
    networks:
      - devtracker-net

volumes:
  user-db-data:
  log-db-data:
  tracking-db-data:
  goal-db-data:
  insight-db-data:
  github-db-data:

networks:
  devtracker-net:
    driver: bridge
