spring:
  application:
    name: tracking-service

  datasource:
    url: jdbc:postgresql://localhost:5434/devtracker_trackingdb
    username: postgres
    password: password12
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          multiplier: 2.0
          max-interval: 10000
    template:
      mandatory: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-adress: true

jwt:
  secret: devTrackerSuperUberSecretKey1231451235
  expiration: 86400000

server:
  port: 8083
