spring:
  application:
    name: github-service

  datasource:
    url: jdbc:postgresql://localhost:5437/devtracker_githubdb
    username: postgres
    password: password12
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-adress: true

jwt:
  secret: devTrackerSuperUberSecretKey1231451235
  expiration: 86400000

server:
  port: 8086
